name: Test and Lint

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Test with pytest
      run: |
        pytest us_sewersheds/ --cov=us_sewersheds --cov-report=xml
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Lint with flake8
      run: |
        flake8 us_sewersheds/ --count --verbose --show-source --statistics
